# Site settings 配置站点
title: 'Ninth Deluxuriment'
description: 'Keep Calm And Code'
keyword: '蒟蒻IOer'
url: 'https://anthonyledger.github.io' # your host
baseurl: ''

# Navigation links
nav:
  home: '/'
  categories: '/categories'
  tags: '/tags'
  activities: '/act'

# Author 配置博主信息
author: 'Deluxurous'
nickname: ''
bio: 'Keep Calm And Code'
avatar: '/assets/img/profile.png'
favicon: '/assets/icons/favicon.png'

# Search
search: true

# Night mode
nightMode: true

# Comments
disqus: true
disqus_url: 'https://deluxurous.disqus.com/embed.js'

# Share
social-share: true
social-share-items: ['wechat', 'qq', 'qzone', 'weibo', 'tencent', 'douban', 'twitter', 'facebook', 'google']

# theme color 主题皮肤
theme-color: 'default'  # pink or default

# Post header background patterns (when the post no cover): circuitBoard, overlappingCircles, food, glamorous, ticTacToe, seaOfClouds
postPatterns: 'ticTacToe'

# SNS settings 配置社交网站url: weibo, zhihu, twitter, instagram, juejin, github, douban, facebook, dribble, uicn, jianshu, medium, linkedin
sns:
  zhihu: 'https://zhihu.com/people/anthony-29-73-28/activities'
  github: 'https://github.com/anthonyledger'
  twitter: 'https://twitter.com/AnthonyLedgerX'
  facebook: 'https://www.facebook.com/anthony.ledger.7509'

# Tags 设置标签
recommend-tags: true # whether or not display recommend-tags on the sidebar
recommend-condition-size: 12 # a tag will be recommended if the size of it is more than this value

# Build settings
paginate: 6
paginate_path: 'page:num'
exclude: ['node_modules', 'dev', 'package.json', 'gulpfile.js', '.gitignore', 'README.md']

# Markdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM

RSS: false

# Plugins
plugins: [jekyll-paginate]

# Friends Link
links:
  'bbbblzy': 'http://blog.csdn.net/bbbblzy'
  'BEYOND_DELIBERATE' : 'https://www.cnblogs.com/the-unbeatable/'
  'czl_233' : 'http://blog.csdn.net/czl_233/'
  'Dance_of_Faith' : 'http://blog.csdn.net/zj_yuneng/'
  'DOlaBMOon' : 'https://www.cnblogs.com/DOlaBMOon/'
  'Effervescence' : 'http://blog.csdn.net/effervescence/'
  'Fire Dancer' : 'http://blog.csdn.net/timsei'
  'HEXU' : 'https://www.cnblogs.com/juruohx'
  'jxcakak' : 'https://www.cnblogs.com/jxcakak/'
  'logic-yzf' : 'https://www.cnblogs.com/logic-yzf/'
  'orbitingflea' : 'https://orbitingflea.github.io/'
  'PinkExSu0v0' : 'http://www.cnblogs.com/whc200305/'
  'Samsara_Karma' : 'http://blog.163.com/James_Chen0306/'
  'tenecnt' : 'https://tenecnt.github.io/'
  'tttnns-blog' : 'https://tttnns-blog.readthedocs.io/'
  'Styx-ferryman' : 'http://www.cnblogs.com/stxy-ferryman/'
  'zjh_2017' : 'http://blog.csdn.net/zjh_2017'
  '柴犬首相': 'http://blog.csdn.net/qq_39670434'
  '咸鱼Fey' : 'https://www.cnblogs.com/sffey/'